"""add cubes mining_sessions ad_views ledger_entries reward_fund

Revision ID: 8417f9e26bc6
Revises: 125fe0e53127
Create Date: 2026-07-22 00:45:51.393729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8417f9e26bc6'
down_revision: Union[str, None] = '125fe0e53127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_fund',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_in', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_out', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_reward_fund_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "INSERT INTO reward_fund (id, balance, total_in, total_out, updated_at) "
        "VALUES (1, 0, 0, 0, now())"
    )
    op.create_table('ad_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ad_network', sa.String(length=50), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'rejected')", name='ck_ad_views_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_views_status'), 'ad_views', ['status'], unique=False)
    op.create_index(op.f('ix_ad_views_user_id'), 'ad_views', ['user_id'], unique=False)
    op.create_table('cubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('bonus_chance', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('comum', 'raro', 'epico', 'lendario', 'mitico')", name='ck_cubes_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubes_user_id'), 'cubes', ['user_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('reward', 'withdrawal', 'bonus', 'fee')", name='ck_ledger_entries_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.create_index('ix_ledger_entries_user_id_created_at', 'ledger_entries', ['user_id', 'created_at'], unique=False)
    op.create_table('mining_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cube_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('ad_view_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('running', 'collected', 'expired')", name='ck_mining_sessions_status'),
    sa.ForeignKeyConstraint(['ad_view_id'], ['ad_views.id'], ),
    sa.ForeignKeyConstraint(['cube_id'], ['cubes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_sessions_ad_view_id'), 'mining_sessions', ['ad_view_id'], unique=False)
    op.create_index(op.f('ix_mining_sessions_cube_id'), 'mining_sessions', ['cube_id'], unique=False)
    op.create_index(op.f('ix_mining_sessions_status'), 'mining_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_mining_sessions_user_id'), 'mining_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mining_sessions_user_id'), table_name='mining_sessions')
    op.drop_index(op.f('ix_mining_sessions_status'), table_name='mining_sessions')
    op.drop_index(op.f('ix_mining_sessions_cube_id'), table_name='mining_sessions')
    op.drop_index(op.f('ix_mining_sessions_ad_view_id'), table_name='mining_sessions')
    op.drop_table('mining_sessions')
    op.drop_index('ix_ledger_entries_user_id_created_at', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_cubes_user_id'), table_name='cubes')
    op.drop_table('cubes')
    op.drop_index(op.f('ix_ad_views_user_id'), table_name='ad_views')
    op.drop_index(op.f('ix_ad_views_status'), table_name='ad_views')
    op.drop_table('ad_views')
    op.drop_table('reward_fund')
    # ### end Alembic commands ###
